export const hotelConfig = {
  name: "Mahashivaya Guest House",
  shortName: "Mahashivaya",
  tagline: "Stay Close to Mahakal",
  editorialSub: "A warm and comfortable stay in Ujjain, just minutes from Mahakaleshwar Temple and Mahakal Lok. Experience peaceful rest and genuine sacred hospitality.",
  location: {
    address: "99 Begampura Marg, Ravishankar Nagar, Near Godha Puliya, Suraj Nagar",
    city: "Ujjain",
    state: "Madhya Pradesh",
    pincode: "456006",
    country: "India",
    fullAddress: "99 Begampura Marg, Ravishankar Nagar, Near Godha Puliya, Suraj Nagar, Ujjain, Madhya Pradesh 456006",
    googleMapsUrl: "https://maps.google.com/?q=Mahashivaya+Guest+House+Begampura+Ujjain",
    coordinates: {
      lat: 23.1765,
      lng: 75.7682,
    },
  },
  contact: {
    phone: "+918269757720",
    phoneDisplay: "+91 82697 57720",
    whatsapp: "918269757720",
    whatsappDisplay: "+91 82697 57720",
    whatsappUrl: "https://wa.me/918269757720?text=Namaste,%20I%20would%20like%20to%20enquire%20about%20booking%20a%20room%20at%20Mahashivaya%20Guest%20House,%20Ujjain.",
    email: "info@mahashivayaguesthouse.com",
    hours: "Available 24/7 (Front Desk: 9 AM - 9 PM Dedicated Support)",
  },
  social: {
    instagram: "https://instagram.com/mahashivaya_ujjain",
    facebook: "https://facebook.com/mahashivayaguesthouse",
    tripadvisor: "https://tripadvisor.com",
  },
  keyDistances: [
    { name: "Mahakal Lok Corridor", distance: "730 m", time: "5 mins walk / e-rickshaw", icon: "near_me" },
    { name: "Mahakaleshwar Temple", distance: "980 m", time: "8 mins walk", icon: "temple_hindu" },
    { name: "Ram Ghat (Shipra River)", distance: "1.4 km", time: "8 mins", icon: "water" },
    { name: "Harsiddhi Temple", distance: "1.2 km", time: "7 mins", icon: "flare" },
    { name: "Ujjain Railway Station", distance: "1.8 km", time: "10 mins", icon: "train" },
    { name: "Ujjain Bus Stand", distance: "2.0 km", time: "8 mins", icon: "directions_bus" },
  ],
  headerNavLinks: [
    { name: "Rooms", href: "/rooms" },
    { name: "Amenities", href: "/amenities" },
    { name: "Gallery", href: "/gallery" },
    { name: "Explore Ujjain", href: "/explore-ujjain" },
    { name: "About", href: "/about" },
  ],
  navLinks: [
    { name: "Home", href: "/" },
    { name: "Rooms", href: "/rooms" },
    { name: "Amenities", href: "/amenities" },
    { name: "Gallery", href: "/gallery" },
    { name: "Explore Ujjain", href: "/explore-ujjain" },
    { name: "About", href: "/about" },
    { name: "Contact", href: "/contact" },
  ],
  otas: [
    {
      id: "makemytrip",
      name: "MakeMyTrip",
      badge: "Popular in India",
      url: "https://www.makemytrip.com/hotels/hotel-listing/?city=UJJAIN",
      description: "Instant confirmation with UPI & all major Indian payment options",
    },
    {
      id: "booking",
      name: "Booking.com",
      badge: "Global Choice",
      url: "https://www.booking.com/city/in/ujjain.html",
      description: "Verified guest reviews and flexible booking options",
    },
    {
      id: "agoda",
      name: "Agoda",
      badge: "Best Rates",
      url: "https://www.agoda.com/city/ujjain-in.html",
      description: "Competitive packages and worldwide pilgrim points",
    },
    {
      id: "goibibo",
      name: "Goibibo",
      badge: "Fast Booking",
      url: "https://www.goibibo.com/hotels/hotels-in-ujjain/",
      description: "Smooth app experience and instant booking voucher",
    },
  ],
};
